# Generated by Django 5.0.1 on 2024-01-12 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('cantidad_prestada', models.IntegerField()),
                ('estado_prestamo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('rut_supervisor', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre_supervisor', models.CharField(max_length=100)),
                ('apellido_supervisor', models.CharField(max_length=100)),
                ('correo_supervisor', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut_usuario', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('apellido_usuario', models.CharField(max_length=100)),
                ('correo_usuario', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('numero_uv_objeto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_objeto', models.CharField(max_length=100)),
                ('fotografia_objeto', models.ImageField(upload_to='objetos/')),
                ('cantidad_objeto', models.IntegerField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.categoria')),
                ('id_prestamo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.prestamo')),
            ],
        ),
        migrations.AddField(
            model_name='prestamo',
            name='rut_supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supervisor'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='rut_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.usuario'),
        ),
    ]
